
function mdl = A3_part2_build()
% Auto-generated by ChatGPT — ECSE 563 A3
% Builds a single-area primary (and optionally secondary) frequency control model.
%
% To run:
%   A3_part2_build();
%   set_param(bdroot, 'StopTime', '{stop_time}');
%   sim(bdroot);
%
% Requirements: Simulink (continuous blocks).

evalin('base','A3_params');  % load parameters into base workspace
mdl = 'A3_part2_build';
new_system(mdl); open_system(mdl);

% ---------------- Layout helpers ----------------
x0 = 30; y0 = 50; dx = 110; dy = 70;
row = @(r) y0 + (r-1)*dy;
col = @(c) x0 + (c-1)*dx;
pos = @(c,r) [col(c) row(r) col(c)+60 row(r)+40];

% ---------------- Source: load step ----------------
add_block('simulink/Sources/Step', [mdl '/LoadStep'], ...
    'Time', '0', 'Before', '0', 'After', 'DeltaP', 'SampleTime', '-1', ...
    'Position', pos(1,4));

% ---------------- Signal for frequency (Hz) ----------------
add_block('simulink/Continuous/Gain', [mdl '/1_over_M'], ...
    'Gain', '1/M', 'Position', pos(6,3));
add_block('simulink/Continuous/Integrator', [mdl '/Int_f'], ...
    'InitialCondition', '0', 'Position', pos(7,3));
add_line(mdl, 'SumP/1', '1_over_M/1');
add_line(mdl, '1_over_M/1', 'Int_f/1');

% ---------------- D*f block ----------------
add_block('simulink/Math Operations/Gain', [mdl '/D_gain'], ...
    'Gain', 'D', 'Position', pos(6,4));
add_line(mdl, 'Int_f/1', 'D_gain/1');

% ---------------- Primary control — Gen1 ----------------
add_block('simulink/Math Operations/Gain', [mdl '/Droop1'], ...
    'Gain', '-invR1', 'Position', pos(4,2));
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Gov1'], ...
    'Numerator', '[1]', 'Denominator', '[TG1 1]', 'Position', pos(5,2));
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Turb1'], ...
    'Numerator', '[1]', 'Denominator', '[TCH1 1]', 'Position', pos(6,2));

% Optional rate limiter for Part 1(e)
add_block('simulink/Discontinuities/Rate Limiter', [mdl '/RateLimit1'], ...
    'RisingSlewLimit', '1', 'FallingSlewLimit', '1', 'SampleTime', '0', ...
    'Position', pos(7,2));
% By default, comment the rate limiter; Part 1e will un-comment it.
set_param([mdl '/RateLimit1'], 'Commented', 'on');

% ---------------- Primary control — Gen2 ----------------
add_block('simulink/Math Operations/Gain', [mdl '/Droop2'], ...
    'Gain', '-invR2', 'Position', pos(4,5));
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Gov2'], ...
    'Numerator', '[1]', 'Denominator', '[TG2 1]', 'Position', pos(5,5));
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Turb2'], ...
    'Numerator', '[1]', 'Denominator', '[TCH2 1]', 'Position', pos(6,5));

% ---------------- Secondary (AGC) integrator & participation ----------------

% AGC Integrator: u' = Ki_AGC * (-f)
add_block('simulink/Math Operations/Gain', [mdl '/Ki'], 'Gain', 'Ki_AGC', 'Position', pos(1,3));
add_block('simulink/Math Operations/Gain', [mdl '/Neg_f'], 'Gain', '-1', 'Position', pos(1,2));
add_block('simulink/Continuous/Integrator', [mdl '/Int_u'], 'InitialCondition', '0', 'Position', pos(2,3));
add_line(mdl, 'Int_f/1', 'Neg_f/1');
add_line(mdl, 'Neg_f/1', 'Ki/1');
add_line(mdl, 'Ki/1', 'Int_u/1');

% Participation split
add_block('simulink/Math Operations/Gain', [mdl '/a1'], 'Gain', 'a1', 'Position', pos(2,2));
add_block('simulink/Math Operations/Gain', [mdl '/a2'], 'Gain', 'a2', 'Position', pos(2,5));
add_line(mdl, 'Int_u/1', 'a1/1');
add_line(mdl, 'Int_u/1', 'a2/1');

% Pref signals
add_block('simulink/Sinks/Terminator', [mdl '/Pref1'], 'Position', pos(2,2)); % placeholder
add_block('simulink/Sinks/Terminator', [mdl '/Pref2'], 'Position', pos(2,5)); % placeholder
replace_block(mdl, 'Name', 'Pref1', 'simulink/Sinks/Terminator', 'simulink/Sinks/Terminator', 'noprompt');
replace_block(mdl, 'Name', 'Pref2', 'simulink/Sinks/Terminator', 'simulink/Sinks/Terminator', 'noprompt');

add_block('simulink/Signal Routing/Goto', [mdl '/Pref_bus'], 'GotoTag', 'PREF', 'Position', pos(2,3));

% Use Goto/From to split
add_block('simulink/Signal Routing/From', [mdl '/FromPref1'], 'GotoTag', 'PREF', 'Position', pos(3,2));
add_block('simulink/Signal Routing/From', [mdl '/FromPref2'], 'GotoTag', 'PREF', 'Position', pos(3,5));

% Actually wire a1*u->Pref1 and a2*u->Pref2
delete_block([mdl '/Pref1']); delete_block([mdl '/Pref2']);
add_block('simulink/Sinks/Terminator', [mdl '/Pm1'], 'Position', pos(8,2)); % pass-through
add_block('simulink/Sinks/Terminator', [mdl '/Pm2'], 'Position', pos(8,5));
add_block('simulink/Sources/From Workspace', [mdl '/Pref1'], 'VariableName', ' ', 'Position', pos(2,2)); % placeholder
add_block('simulink/Sources/From Workspace', [mdl '/Pref2'], 'VariableName', ' ', 'Position', pos(2,5));
delete_block([mdl '/Pref1']); delete_block([mdl '/Pref2']);

add_block('simulink/Sinks/Terminator', [mdl '/Term1'], 'Position', pos(2,2));
add_block('simulink/Sinks/Terminator', [mdl '/Term2'], 'Position', pos(2,5));
delete_block([mdl '/Term1']); delete_block([mdl '/Term2']);

add_block('simulink/Sinks/Terminator', [mdl '/unused'], 'Position', pos(2,3)); delete_block([mdl '/unused']);

add_block('simulink/Signal Routing/Signal Conversion', [mdl '/Pref1'], 'Position', pos(2,2));
add_block('simulink/Signal Routing/Signal Conversion', [mdl '/Pref2'], 'Position', pos(2,5));
add_line(mdl, 'a1/1', 'Pref1/1');
add_line(mdl, 'a2/1', 'Pref2/1');


% ---------------- Sums to form mechanical powers ----------------
add_block('simulink/Math Operations/Sum', [mdl '/Sum1'], ...
    'Inputs', '++', 'Position', pos(3,2));
add_block('simulink/Math Operations/Sum', [mdl '/Sum2'], ...
    'Inputs', '++', 'Position', pos(3,5));

% Connect f -> droops
add_line(mdl, 'Int_f/1', 'Droop1/1');
add_line(mdl, 'Int_f/1', 'Droop2/1');

% Sum Pref + Droop for each gen
add_line(mdl, 'Pref1/1', 'Sum1/1');
add_line(mdl, 'Droop1/1', 'Sum1/2');
add_line(mdl, 'Pref2/1', 'Sum2/1');
add_line(mdl, 'Droop2/1', 'Sum2/2');

% Cascades
add_line(mdl, 'Sum1/1', 'Gov1/1');
add_line(mdl, 'Gov1/1', 'Turb1/1');
add_line(mdl, 'Turb1/1', 'RateLimit1/1');
add_line(mdl, 'RateLimit1/1', 'Pm1/1');

add_line(mdl, 'Sum2/1', 'Gov2/1');
add_line(mdl, 'Gov2/1', 'Turb2/1');
add_line(mdl, 'Turb2/1', 'Pm2/1');

% ---------------- Sum of powers for swing equation ----------------
add_block('simulink/Math Operations/Sum', [mdl '/SumP'], ...
    'Inputs', '++-+', 'Position', pos(5,3));

% Connect Pm1, Pm2, LoadStep, D*f to SumP
add_line(mdl, 'Pm1/1', 'SumP/1');
add_line(mdl, 'Pm2/1', 'SumP/2');
add_line(mdl, 'LoadStep/1', 'SumP/3');
add_line(mdl, 'D_gain/1', 'SumP/4');

% ---------------- Scopes & logging ----------------
add_block('simulink/Sinks/Scope', [mdl '/Scope_f'], 'Position', pos(9,3));
add_line(mdl, 'Int_f/1', 'Scope_f/1');

add_block('simulink/Signal Routing/Mux', [mdl '/MuxPm'], 'Inputs', '2', 'Position', pos(8,5));
add_block('simulink/Sinks/Scope', [mdl '/Scope_Pm'], 'Position', pos(9,5));
add_line(mdl, 'Pm1/1', 'MuxPm/1');
add_line(mdl, 'Pm2/1', 'MuxPm/2');
add_line(mdl, 'MuxPm/1', 'Scope_Pm/1');

% To Workspace
add_block('simulink/Sinks/To Workspace', [mdl '/f_out'], ...
    'VariableName', 'f_Hz', 'SaveFormat', 'StructureWithTime', 'Position', pos(9,2));
add_line(mdl, 'Int_f/1', 'f_out/1');
add_block('simulink/Sinks/To Workspace', [mdl '/Pm_out'], ...
    'VariableName', 'Pm_MW', 'SaveFormat', 'StructureWithTime', 'Position', pos(9,6));
add_line(mdl, 'MuxPm/1', 'Pm_out/1');

% Save & set stop time
set_param(mdl, 'StopTime', '{stop_time}');
save_system(mdl);
end
